---
- hosts: localhost

  vars:
    datacenter: 'Datacenter'
    #esxi_host: 'esxi-1.labvmware.local'
    notes: 'Created by Ansible'
    datastore: DatastoreCluster
    network: VM Network
    memory: 512
    cpucount: 1
    osid: centos64Guest

  tasks:
  - name: Create a VM from template
    vmware_guest:
      hostname: "{{vcenter_hostname}}"
      username: "{{vcenter_user}}"
      password: "{{vcenter_pass}}"
      cluster: clusterESGI
      validate_certs: no
      datacenter: "{{datacenter}}"
      folder: /Datacenter/vm
      name: testvmff111_3
      state: present
      guest_id: "{{osid}}"
      #template: vm1
      disk:
      - size_gb: 1
        type: thin
        datastore: "{{datastore}}"
      hardware:
        memory_mb: "{{memory}}"
        num_cpus: "{{cpucount}}"
        scsi: paravirtual
#      networks:
#      - name: 'VM Network'
#        mac: aa:bb:dd:aa:00:14
      wait_for_ip_address: no #yes
#    delegate_to: localhost
    register: deploy    #_vm
