---
- name: Warn logged in users of impending upgrade
  hosts: windows_server
  tasks:
  - name: TEST
    win_msg:
      display_seconds: 60
      msg: Automated upgrade about to start.  Please save your work and log off before
