---
- name: Maintenance on TSE
  hosts: windows_server 

  vars:
      Message: Toto

  tasks:
  - name: Ping TSE
    win_ping:

  - name: send msg
    win_shell: msg.exe /server:dc-01.labvmware.local * "{{ Message }}"
